# Generated by Django 5.1.4 on 2025-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to='properties.owner'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(unique=True),
        ),
    ]
