# Generated by Django 5.1.4 on 2025-02-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_owner_property_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owners',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.owner'),
        ),
    ]
